services:
  db:
    image: postgres:15
    container_name: clinixtech_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: clinixtech
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: clinixtech_mq
    restart: always
    ports:
      - "5672:5672"   # Porta do servi√ßo
      - "15672:15672" # Porta do painel administrativo (User/Pass: guest)